import { Animation, Assets } from "@latticexyz/phaserx/src/types";

export const animationConfig: Animation<Assets>[] = [
  {
    key: "mainbase/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level1/Main_Base_LVL1_",
    suffix: ".png",
  },
  {
    key: "mainbase/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level2/Main_Base_LVL2_",
    suffix: ".png",
  },
  {
    key: "mainbase/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level3/Main_Base_LVL3_",
    suffix: ".png",
  },
  {
    key: "mainbase/level4",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level4/Main_Base_LVL4_",
    suffix: ".png",
  },
  {
    key: "mainbase/level5",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level5/Main_Base_LVL5_",
    suffix: ".png",
  },
  {
    key: "mainbase/level6",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level6/Main_Base_LVL6_",
    suffix: ".png",
  },
  {
    key: "mainbase/level7",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level7/Main_Base_LVL7_",
    suffix: ".png",
  },
  {
    key: "mainbase/level8",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 10,
    repeat: -1,
    prefix: "sprites/mainbase/level8/Main_Base_LVL8_",
    suffix: ".png",
  },
  {
    key: "ironmine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/ironmine/level1/Miner_Iron_LVL1_",
    suffix: ".png",
  },
  {
    key: "ironmine/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/ironmine/level2/Miner_Iron_LVL2_",
    suffix: ".png",
  },
  {
    key: "ironmine/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/ironmine/level3/Miner_Iron_LVL3_",
    suffix: ".png",
  },
  {
    key: "coppermine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/coppermine/level1/Miner_Copper_LVL1_",
    suffix: ".png",
  },
  {
    key: "coppermine/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/coppermine/level2/Miner_Copper_LVL2_",
    suffix: ".png",
  },
  {
    key: "coppermine/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/coppermine/level3/Miner_Copper_LVL3_",
    suffix: ".png",
  },
  {
    key: "lithiummine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/lithiummine/Miner_Lithium_LVL1_",
    suffix: ".png",
  },
  {
    key: "kimberlitemine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/kimberlitemine/level1/Miner_Kimberlite_LVL1_",
    suffix: ".png",
  },
  {
    key: "kimberlitemine/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/kimberlitemine/level2/Miner_Kimberlite_LVL2_",
    suffix: ".png",
  },
  {
    key: "kimberlitemine/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/kimberlitemine/level3/Miner_Kimberlite_LVL3_",
    suffix: ".png",
  },
  {
    key: "iridiummine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/iridiummine/level1/Miner_Iridium_LVL1_",
    suffix: ".png",
  },
  {
    key: "iridiummine/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/iridiummine/level2/Miner_Iridium_LVL2_",
    suffix: ".png",
  },
  {
    key: "iridiummine/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/iridiummine/level3/Miner_Iridium_LVL3_",
    suffix: ".png",
  },
  {
    key: "platinummine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/platinummine/level1/Miner_Platinum_LVL1_",
    suffix: ".png",
  },
  {
    key: "platinummine/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/platinummine/level2/Miner_Platinum_LVL2_",
    suffix: ".png",
  },
  {
    key: "platinummine/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/platinummine/level3/Miner_Platinum_LVL3_",
    suffix: ".png",
  },
  {
    key: "titaniummine/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/titaniummine/level1/Miner_Titanium_LVL1_",
    suffix: ".png",
  },
  {
    key: "titaniummine/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/titaniummine/level2/Miner_Titanium_LVL2_",
    suffix: ".png",
  },
  {
    key: "titaniummine/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/miners/titaniummine/level3/Miner_Titanium_LVL3_",
    suffix: ".png",
  },
  {
    key: "alloyfactory/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/alloy-factory/level1/Alloy_Factory",
    suffix: ".png",
  },
  {
    key: "alloyfactory/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/alloy-factory/level2/Alloy_Factory_LVL2_",
    suffix: ".png",
  },
  {
    key: "alloyfactory/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/alloy-factory/level3/Alloy_Factory_LVL3_",
    suffix: ".png",
  },
  {
    key: "pvcfactory/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 7,
    repeat: -1,
    prefix: "sprites/photovoltaic-cell-factory/level1/Photovoltaic_Factory_LVL1_",
    suffix: ".png",
  },
  {
    key: "pvcfactory/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 7,
    repeat: -1,
    prefix: "sprites/photovoltaic-cell-factory/level2/Photovoltaic_Factory_LVL2_",
    suffix: ".png",
  },
  {
    key: "ironplatefactory/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/plating-factory/level1/Plating_Factory_LVL1_",
    suffix: ".png",
  },
  {
    key: "ironplatefactory/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/plating-factory/level2/Plating_Factory_LVL2_",
    suffix: ".png",
  },
  {
    key: "storageunit/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/storage-facility/level3/Storage_Facility_LVL3_",
    suffix: ".png",
  },
  {
    key: "solarpanel/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 18,
    repeat: -1,
    prefix: "sprites/solar-panels/level1/Solar_Panels_LVL1_",
    suffix: ".png",
  },
  {
    key: "solarpanel/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 18,
    repeat: -1,
    prefix: "sprites/solar-panels/level2/Solar_Panels_LVL2_",
    suffix: ".png",
  },
  {
    key: "starmapperstation/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 15,
    repeat: -1,
    prefix: "sprites/starmapper-station/level1/Starmapper",
    suffix: ".png",
  },
  {
    key: "starmapperstation/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 15,
    repeat: -1,
    prefix: "sprites/starmapper-station/level2/Starmapper_LVL2_",
    suffix: ".png",
  },
  {
    key: "starmapperstation/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 15,
    repeat: -1,
    prefix: "sprites/starmapper-station/level3/Starmapper_LVL3_",
    suffix: ".png",
  },
  {
    key: "garage/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 7,
    repeat: -1,
    prefix: "sprites/garage/level1/Garage_LVL1_",
    suffix: ".png",
  },
  {
    key: "garage/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 7,
    repeat: -1,
    prefix: "sprites/garage/level2/Garage_LVL2_",
    suffix: ".png",
  },
  {
    key: "hangar/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 9,
    repeat: -1,
    prefix: "sprites/hangar/level1/Hangar",
    suffix: ".png",
  },
  {
    key: "workshop/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 11,
    repeat: -1,
    prefix: "sprites/workshop/level1/Workshop_LVL1_",
    suffix: ".png",
  },
  {
    key: "workshop/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 11,
    repeat: -1,
    prefix: "sprites/workshop/level2/Workshop_LVL2_",
    suffix: ".png",
  },
  {
    key: "workshop/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 11,
    repeat: -1,
    prefix: "sprites/workshop/level3/Workshop_LVL3_",
    suffix: ".png",
  },
  {
    key: "dronefactory/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 14,
    repeat: -1,
    prefix: "sprites/drone-factory/normal/Drone_Factory",
    suffix: ".png",
  },
  {
    key: "samlauncher/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/sam_launcher/level1/SAM_Launcher_LVL1_",
    suffix: ".png",
  },
  {
    key: "samlauncher/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 13,
    repeat: -1,
    prefix: "sprites/sam_launcher/level2/SAM_Launcher_LVL2_",
    suffix: ".png",
  },
  {
    key: "samlauncher/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 13,
    repeat: -1,
    prefix: "sprites/sam_launcher/level3/SAM_Launcher_LVL3_",
    suffix: ".png",
  },
  {
    key: "shieldgenerator/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 11,
    repeat: -1,
    prefix: "sprites/shield-generator/level1/Shield_Generator_LVL1_",
    suffix: ".png",
  },
  {
    key: "shieldgenerator/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 11,
    repeat: -1,
    prefix: "sprites/shield-generator/level2/Shield_Generator_LVL2_",
    suffix: ".png",
  },
  {
    key: "shieldgenerator/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 11,
    repeat: -1,
    prefix: "sprites/shield-generator/level3/Shield_Generator_LVL3_",
    suffix: ".png",
  },
  {
    key: "vault/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 15,
    repeat: -1,
    prefix: "sprites/vault/level1/Vault_LVL1_",
    suffix: ".png",
  },
  {
    key: "vault/level2",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 15,
    repeat: -1,
    prefix: "sprites/vault/level2/Vault_LVL2_",
    suffix: ".png",
  },
  {
    key: "vault/level3",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 15,
    repeat: -1,
    prefix: "sprites/vault/level3/Vault_LVL3_",
    suffix: ".png",
  },
  {
    key: "marketplace/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 6,
    repeat: -1,
    prefix: "sprites/marketplace/level1/Marketplace_LVL1_",
    suffix: ".png",
  },
  {
    key: "shipyard/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 17,
    repeat: -1,
    prefix: "sprites/shipyard/level1/Shipyard_LVL1_",
    suffix: ".png",
  },
  {
    key: "droidbase/level1",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 8,
    repeat: -1,
    prefix: "sprites/droidbase/Droid_Base",
    suffix: ".png",
  },
  {
    key: "decorations/drone",
    assetKey: "sprite-atlas",
    frameRate: 5,
    startFrame: 1,
    endFrame: 12,
    repeat: -1,
    prefix: "sprites/decorations/drone/Drone",
    suffix: ".png",
  },
];
