// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Counter } from "./tables/Counter.sol";
import { Position } from "./tables/Position.sol";
import { Inventory, InventoryData } from "./tables/Inventory.sol";
