name: Test suites for @primodiumxyz/react-tables

on: [push]

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.2"

      - name: Install pnpm
        run: npm install -g pnpm@8.15.7

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Start Foundry Node
        run: pnpm dev:node &

      - name: Add Foundry private key
        run: echo "PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" > __tests__/contracts/.env

      - name: Deploy contracts
        run: pnpm dev:contracts

      - name: Run tests in contracts
        run: pnpm run test
